package log

type LoggerIcon string

const (
	IconHammer           LoggerIcon = "\xF0\x9F\x94\xA8"
	IconFire             LoggerIcon = "\xF0\x9F\x94\xA5"
	IconWrench           LoggerIcon = "\xF0\x9F\x94\xA7"
	IconKey              LoggerIcon = "\xF0\x9F\x94\x91"
	IconLock             LoggerIcon = "\xF0\x9F\x94\x92"
	IconOpenLock         LoggerIcon = "\xF0\x9F\x94\x93"
	IconBell             LoggerIcon = "\xF0\x9F\x94\x94"
	IconMagnifyingGlass  LoggerIcon = "\xF0\x9F\x94\x8D"
	IconBook             LoggerIcon = "\xF0\x9F\x93\x94"
	IconBulb             LoggerIcon = "\xF0\x9F\x92\xA1"
	IconBomb             LoggerIcon = "\xF0\x9F\x92\xA3"
	IconLargeWhiteSquare LoggerIcon = "\xE2\xAC\x9C"
	IconCircle           LoggerIcon = "\xE2\x9A\xAB"
	IconWarning          LoggerIcon = "\xE2\x9A\xA0"
	IconRightArrow       LoggerIcon = "\xE2\x96\xB6"
	IconHourGlass        LoggerIcon = "\xE2\x8C\x9B"
	IconInfo             LoggerIcon = "\xE2\x84\xB9"
	IconFlag             LoggerIcon = "\xF0\x9F\x9A\xA9"
	IconRocket           LoggerIcon = "\xF0\x9F\x9A\x80"
	IconCheckMark        LoggerIcon = "\xE2\x9C\x85"
	IconCrossMark        LoggerIcon = "\xE2\x9D\x8C"
	IconRevolvingLight   LoggerIcon = "\xF0\x9F\x9A\xA8"
	IconBlackSquare      LoggerIcon = "\xE2\x97\xBE"
	IconFolder           LoggerIcon = "\xF0\x9F\x93\x81"
	IconClipboard        LoggerIcon = "\xF0\x9F\x93\x8B "
	IconRightwardsArrow  LoggerIcon = "\xE2\x96\xB6"
	IconExclamationMark  LoggerIcon = "\xE2\x9D\x95"
	IconAsterisk         LoggerIcon = "\xE2\x9C\xB3"
	IconRightHand        LoggerIcon = "\xF0\x9F\x91\x89"
	IconCheckbox         LoggerIcon = "\xE2\x98\x91"
	IconToilet           LoggerIcon = "	\xF0\x9F\x9A\xBD"
	IconThumbsUp         LoggerIcon = "\xF0\x9F\x91\x8D"
	IconThumbDown        LoggerIcon = "\xF0\x9F\x91\x8E"
	IconPage             LoggerIcon = "\xF0\x9F\x93\x84"
)
